# Generated by Django 4.2.5 on 2023-10-02 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenVideo',
            fields=[
                ('video_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='recorded_videos/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transcription', models.TextField(blank=True)),
            ],
        ),
    ]
