# Generated by Django 4.2.5 on 2023-10-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenvideo',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_videos/'),
        ),
    ]
