# Generated by Django 4.2.5 on 2023-10-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screenapp', '0001_initial'),
    ]

    operations = [
    ]
