# Generated by Django 4.2.5 on 2023-10-02 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screenapp', '0002_auto_20231001_1228'),
    ]

    operations = [
    ]
